FROM node:18.17.0-buster-slim

COPY . /workspace
WORKDIR /workspace

RUN apt-get update && \
    apt-get install -y \
      dh-autoreconf build-essential \
      git make python python-dev

RUN yarn install
